"""Added Submission.votes column

Revision ID: 43c1baca42a2
Revises: 0825e907782f
Create Date: 2021-02-13 23:04:19.573163-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c1baca42a2'
down_revision = '0825e907782f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'votes')
    # ### end Alembic commands ###
